### ISSUE TITLE
The ratio of source and target

### ISSUE THREAD

**Issue by fandulu** [hehaodele/CIDA#1]
Hi Hao, I watched your presentation but missed some points, could I ask what the ratio of labeled source and unlabeled target in your training, and for unlabeled target prediction \hat{y}, how do you regress it? Thanks.

**Comment by hehaodele** [comment]
Hi there, the source/target ratio in the 3 toy datasets are the following: (1) half-circle: 6/9; (2) sine: 5/7; (3) RotatedMNIST: 1/7. You can check the values of `opt.num_domian` and `opt.num_source` in the ipynb files.  
Second, to predict in the target domain, you simply use the predictor you trained in the source domain. It is the common practice of domain adaptation.

**Comment by fandulu** [comment]
Thanks very much to clarify this.
