### ISSUE TITLE
关于代码的问题

### ISSUE THREAD

**Issue by yangdongchao** [hehaodele/CIDA#3]
我发现代码里面有一个问题，你没有划分训练集和测试集？你好像用的是同一个。

**Comment by hehaodele** [comment]
There is a parameter called 'is_source'. During the training only the label in the source domain is available. Let me know if there are any further questions. In the setting of domain adaptation, usually, the model is trained on source domain labeled data + target domain unlabeled data and directly evaluated on the target domain data.

**Comment by sshh12** [comment]
To clarify for those who may be as confused as me by this, it looks like the "train" and "test" loaders in the code actually point to the exact same data. The actual train/test differentiation comes from `self.is_source = (self.domain < 1.0 / 8)` which effectively sets the training data to examples in the domain [0,1/8] (= [0, 45] degrees). The code then uses the "is_source=False" examples in forward passes and for fitting the domain classifier but never actually looks at their labels.

**Comment by hehaodele** [comment]
Thank you Shriver for your kindly clarification to other users. It is a nice explanation.
